# Generated by Django 4.1.1 on 2022-10-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store_app', '0002_alter_product_managers_cartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=50)),
                ('client_address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='orders', to='e_store_app.cartproduct')),
            ],
        ),
    ]
