# Generated by Django 4.1.1 on 2022-10-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store_app', '0004_alter_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_ordered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
