# Generated by Django 4.1.1 on 2022-10-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_store_app', '0005_order_quantity_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity_ordered',
        ),
    ]
